name: {{name.snakeCase()}}
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  ffigen: ^7.2.9
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.72.1
